name: CI
on:
 push:
   branches:
     - main
jobs:
  stage:
    runs-on: self-hosted
    name: build example
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Build images
      run: |
        docker build -t dipak .
        echo -n "verifying images:"
        docker images 
    - name: rollout restart deploy 
      run: |
        kubectl rollout restart deployment prod
    - name: rollout restart deploy 
      run: |
        kubectl rollout restart deployment stage
    
